name: ZerioBasic
version: ${project.version}
main: me.ignjax.zeriobasic.ZerioBasic
authors: [ignJax, StaffTP]

commands:
  ping:
    description: Check your ping!
  discord:
    description: Join our discord!
  forums:
    description: Check out our forums!